// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO Users(
    Id,
    FirstName,
    LastName,
    EmailAddresss,
    Password
) VALUES ($1, $2, $3, $4, $5)

RETURNING id, firstname, lastname, password, emailaddresss
`

type InsertUserParams struct {
	ID            uuid.UUID
	Firstname     string
	Lastname      string
	Emailaddresss string
	Password      string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Emailaddresss,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Password,
		&i.Emailaddresss,
	)
	return i, err
}
